## Copyright (c) 2024 Horizon Robotics. All Rights Reserved.

from __future__ import annotations
import bisect
import io
import json
import math
from collections import Counter, defaultdict
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from google.protobuf.json_format import MessageToDict
from mcap.reader import make_reader
from mcap_protobuf.decoder import DecoderFactory
from PIL import Image, ImageDraw, ImageFont

CAMERA_TOPICS = {
    "ext1": "/observation/cameras/ext1_camera/color_image/image_raw",
    "ext2": "/observation/cameras/ext2_camera/color_image/image_raw",
    "wrist": "/observation/cameras/wrist_camera/color_image/image_raw",
}
CAMERA_INFO_TOPICS = {
    view: topic.replace("/image_raw", "/camera_info")
    for view, topic in CAMERA_TOPICS.items()
}
CAMERA_TF_TOPICS = {
    view: topic.replace("/image_raw", "/tf")
    for view, topic in CAMERA_TOPICS.items()
}
META_TOPIC = "/meta_data"
ROBOT_JOINT_TOPIC = "/robot/joint_states"
GRIPPER_COMMAND_TOPIC = "/action/robot_state/gripper/joint_states"
TARGET_SELECTION_VALUES = {"CORRECT", "WRONG_OBJECT", "UNCERTAIN"}
GRIPPER_ACTION_VALUES = {
    "CLOSE_ATTEMPTED",
    "NO_CLOSE_ATTEMPT",
    "UNKNOWN",
}
TARGET_INTERACTION_VALUES = {
    "NO_CONTACT",
    "CONTACT_NO_GRASP",
    "TRANSIENT_GRASP",
    "STABLE_GRASP",
    "UNKNOWN",
}
OBJECT_OUTCOME_VALUES = {
    "STATIONARY",
    "PUSHED_AWAY",
    "LIFTED_SUCCESSFULLY",
    "LIFTED_THEN_DROPPED",
    "LIFTED_INSUFFICIENTLY",
    "UNKNOWN",
}
CAUSE_VALUES = {
    "NONE",
    "SELECTED_DISTRACTOR",
    "OFF_TARGET_APPROACH",
    "NO_CLOSE_ATTEMPT",
    "MISALIGNED_GRASP",
    "UNSTABLE_GRASP",
    "PREMATURE_GRIPPER_OPENING",
    "INSUFFICIENT_LIFT_MOTION",
    "UNKNOWN",
}
PROVENANCE_WARNING = (
    "Error attributions are generated by a large model using continuous "
    "multi-view images, gripper state, metadata, and evaluation metrics. "
    "They are not human-labelled ground truth."
)


class AnalysisError(RuntimeError):
    """Raised when deterministic pick-failure preparation cannot continue."""


def load_eval_result(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as stream:
        data = json.load(stream)
    if not isinstance(data, dict) or not isinstance(
        data.get("episode_results"), list
    ):
        raise AnalysisError(f"Invalid eval_result.json: {path}")
    return data


def select_episode_results(
    data: Mapping[str, Any],
    *,
    seeds: Sequence[int] | None,
    all_failures: bool,
    include_success: bool,
) -> list[dict[str, Any]]:
    if bool(seeds) == bool(all_failures):
        raise ValueError(
            "Select exactly one of explicit seeds or all_failures"
        )

    episode_results = data.get("episode_results")
    if not isinstance(episode_results, list):
        raise AnalysisError("eval_result.json has no episode_results list")
    by_seed = {
        int(item["seed"]): dict(item)
        for item in episode_results
        if isinstance(item, Mapping) and item.get("seed") is not None
    }
    if seeds:
        missing = [seed for seed in seeds if seed not in by_seed]
        if missing:
            raise AnalysisError(
                f"Seeds missing from eval_result.json: {missing}"
            )
        return [by_seed[seed] for seed in seeds]

    failures = [
        dict(item)
        for item in episode_results
        if isinstance(item, Mapping) and item.get("success") is False
    ]
    if not include_success:
        return failures
    controls = [
        dict(item)
        for item in episode_results
        if isinstance(item, Mapping) and item.get("success") is True
    ]
    return failures + controls


def extract_evaluation_metrics(
    episode_result: Mapping[str, Any],
) -> dict[str, Any]:
    metrics = episode_result.get("metrics")
    criteria_reached = None
    if isinstance(metrics, Mapping):
        candidate = metrics.get("criteria_reached")
        if isinstance(candidate, Mapping):
            criteria_reached = candidate
    return {
        "success": episode_result.get("success"),
        "progress": episode_result.get("progress"),
        "reach_pick": (
            criteria_reached.get("reach_pick") if criteria_reached else None
        ),
        "lift_pick": (
            criteria_reached.get("lift_pick") if criteria_reached else None
        ),
        "steps": episode_result.get("steps"),
        "stop_reason": episode_result.get("stop_reason"),
    }


def reconcile_evaluation_metrics(
    evaluation: Mapping[str, Any],
    metadata: Mapping[str, Any],
) -> dict[str, Any]:
    result = dict(evaluation)
    raw_progress = metadata.get("task_progress")
    task_progress = (
        float(raw_progress) if isinstance(raw_progress, (int, float)) else None
    )
    raw_success = metadata.get("task_success")
    task_success = (
        bool(raw_success)
        if isinstance(raw_success, (bool, int, float))
        else None
    )
    completed = task_progress is not None and task_progress >= 1.0
    overrode = completed and any(
        (
            result.get("success") is not True,
            result.get("progress") != 1.0,
            result.get("reach_pick") is not True,
            result.get("lift_pick") is not True,
            result.get("stop_reason") != "success",
        )
    )
    if completed:
        result.update(
            {
                "success": True,
                "progress": 1.0,
                "reach_pick": True,
                "lift_pick": True,
                "stop_reason": "success",
                "source": "MCAP_TASK_PROGRESS",
            }
        )
    else:
        result["source"] = "EVAL_RESULT"
    result["mcap_task_progress"] = task_progress
    result["mcap_task_success"] = task_success
    result["overrode_external_result"] = overrode
    return result


def discover_mcap(eval_root: Path, seed: int) -> Path:
    matches = sorted(
        path
        for path in eval_root.rglob("*.mcap")
        if f"seed_{seed}" in path.as_posix()
    )
    if not matches:
        raise AnalysisError(f"No MCAP found for seed {seed}")
    if len(matches) > 1:
        raise AnalysisError(
            f"Multiple MCAP files found for seed {seed}: {matches}"
        )
    return matches[0]


def nearest_timestamp_index(timestamps: Sequence[int], target: int) -> int:
    if not timestamps:
        raise ValueError("timestamps must not be empty")
    insertion = bisect.bisect_left(timestamps, target)
    if insertion == 0:
        return 0
    if insertion == len(timestamps):
        return len(timestamps) - 1
    before = timestamps[insertion - 1]
    after = timestamps[insertion]
    if target - before < after - target:
        return insertion - 1
    return insertion


def detect_close_intervals(
    samples: Sequence[tuple[int, float]],
    *,
    minimum_delta: float = 0.3,
    closed_threshold: float = 0.6,
    minimum_samples: int = 2,
) -> list[dict[str, Any]]:
    if minimum_samples < 1:
        raise ValueError("minimum_samples must be positive")
    if not samples:
        return []

    intervals = []
    baseline_index = 0
    baseline = float(samples[0][1])
    candidate_start = None
    closed_count = 0
    peak = baseline
    armed = True
    reopen_threshold = closed_threshold - minimum_delta / 2

    for index, (_, raw_position) in enumerate(samples):
        position = float(raw_position)
        if not armed:
            if position < reopen_threshold:
                armed = True
                baseline = position
                baseline_index = index
            continue

        if candidate_start is None and position < baseline:
            baseline = position
            baseline_index = index

        if candidate_start is None and position - baseline >= minimum_delta:
            candidate_start = min(index - 1, baseline_index + 1)
            candidate_start = max(0, candidate_start)
            peak = position

        if candidate_start is None:
            continue

        peak = max(peak, position)
        if position >= closed_threshold:
            closed_count += 1
        else:
            closed_count = 0

        if closed_count >= minimum_samples:
            intervals.append(
                {
                    "start_index": candidate_start,
                    "end_index": index,
                    "peak_position": round(peak, 6),
                }
            )
            candidate_start = None
            closed_count = 0
            armed = False

    return intervals


def summarize_gripper_trace(
    samples: Sequence[tuple[int, float]],
    *,
    minimum_delta: float = 0.3,
    closed_threshold: float = 0.6,
    minimum_samples: int = 2,
) -> dict[str, Any]:
    if not samples:
        return {
            "status": "UNKNOWN",
            "samples": [],
            "close_intervals": [],
        }
    intervals = detect_close_intervals(
        samples,
        minimum_delta=minimum_delta,
        closed_threshold=closed_threshold,
        minimum_samples=minimum_samples,
    )
    return {
        "status": "AVAILABLE",
        "samples": [
            {"timestamp_ns": timestamp, "position": position}
            for timestamp, position in samples
        ],
        "close_intervals": intervals,
        "thresholds": {
            "minimum_delta": minimum_delta,
            "closed_threshold": closed_threshold,
            "minimum_samples": minimum_samples,
        },
    }


def _extract_target(metadata: Mapping[str, Any]) -> dict[str, Any]:
    actors = metadata.get("actors")
    if not isinstance(actors, Mapping):
        return {}
    candidates = []
    for actor_path, actor in actors.items():
        if isinstance(actor, Mapping) and actor.get("actor_type") == "pick":
            candidates.append((actor_path, actor))
    if len(candidates) != 1:
        return {}
    actor_path, actor = candidates[0]
    initial_positions = metadata.get("init_position")
    final_positions = metadata.get("final_position")
    return {
        "actor_path": actor_path,
        "category": actor.get("actor_category"),
        "uuid": actor.get("actor_uuid"),
        "actor_type": actor.get("actor_type"),
        "initial_pose": (
            initial_positions.get(actor_path)
            if isinstance(initial_positions, Mapping)
            else None
        ),
        "final_pose": (
            final_positions.get(actor_path)
            if isinstance(final_positions, Mapping)
            else None
        ),
    }


def _joint_position(decoded: Any, joint_name: str) -> float | None:
    for state in decoded.states:
        if state.name == joint_name:
            return float(state.position)
    return None


def _quaternion_rotation_matrix(
    quaternion_xyzw: Sequence[float],
) -> list[list[float]]:
    x, y, z, w = [float(value) for value in quaternion_xyzw]
    norm = math.sqrt(x * x + y * y + z * z + w * w)
    if norm == 0:
        raise ValueError("camera quaternion must be non-zero")
    x, y, z, w = [value / norm for value in (x, y, z, w)]
    return [
        [
            1 - 2 * (y * y + z * z),
            2 * (x * y - z * w),
            2 * (x * z + y * w),
        ],
        [
            2 * (x * y + z * w),
            1 - 2 * (x * x + z * z),
            2 * (y * z - x * w),
        ],
        [
            2 * (x * z - y * w),
            2 * (y * z + x * w),
            1 - 2 * (x * x + y * y),
        ],
    ]


def project_point_to_image(
    *,
    point: Sequence[float],
    camera_translation: Sequence[float],
    camera_quaternion_xyzw: Sequence[float],
    intrinsic_matrix: Sequence[float],
    image_size: tuple[int, int],
) -> dict[str, Any] | None:
    if len(point) < 3 or len(intrinsic_matrix) != 9:
        raise ValueError("point and intrinsic matrix have invalid dimensions")
    rotation = _quaternion_rotation_matrix(camera_quaternion_xyzw)
    delta = [
        float(point[index]) - float(camera_translation[index])
        for index in range(3)
    ]
    point_camera = [
        sum(rotation[row][column] * delta[row] for row in range(3))
        for column in range(3)
    ]
    if point_camera[2] <= 0:
        return None
    u = float(intrinsic_matrix[0]) * point_camera[0] / point_camera[2] + float(
        intrinsic_matrix[2]
    )
    v = float(intrinsic_matrix[4]) * point_camera[1] / point_camera[2] + float(
        intrinsic_matrix[5]
    )
    width, height = image_size
    return {
        "u": round(u, 6),
        "v": round(v, 6),
        "normalized": [round(u / width, 6), round(v / height, 6)],
    }


def extract_mcap_manifest(
    mcap_path: Path,
    *,
    minimum_delta: float = 0.3,
    closed_threshold: float = 0.6,
    minimum_samples: int = 2,
) -> dict[str, Any]:
    camera_frames = {
        view: {"indexes": [], "timestamps_ns": []} for view in CAMERA_TOPICS
    }
    camera_calibration = {}
    camera_transforms = {}
    metadata = {}
    actual_gripper_samples = []
    command_gripper_samples = []
    topics = (
        list(CAMERA_TOPICS.values())
        + list(CAMERA_INFO_TOPICS.values())
        + list(CAMERA_TF_TOPICS.values())
        + [META_TOPIC, ROBOT_JOINT_TOPIC, GRIPPER_COMMAND_TOPIC]
    )
    with mcap_path.open("rb") as stream:
        reader = make_reader(stream, decoder_factories=[DecoderFactory()])
        for _, channel, message, decoded in reader.iter_decoded_messages(
            topics=topics
        ):
            topic = channel.topic
            if topic == META_TOPIC:
                metadata = MessageToDict(
                    decoded, preserving_proto_field_name=True
                )
                continue
            if topic == ROBOT_JOINT_TOPIC:
                position = _joint_position(decoded, "panda_joint8")
                if position is not None:
                    actual_gripper_samples.append((message.log_time, position))
                continue
            if topic == GRIPPER_COMMAND_TOPIC:
                position = _joint_position(decoded, "joint1")
                if position is not None:
                    command_gripper_samples.append(
                        (message.log_time, position)
                    )
                continue
            for view, info_topic in CAMERA_INFO_TOPICS.items():
                if topic == info_topic and view not in camera_calibration:
                    camera_calibration[view] = {
                        "width": int(decoded.width),
                        "height": int(decoded.height),
                        "K": [float(value) for value in decoded.K],
                    }
                    break
            else:
                for view, tf_topic in CAMERA_TF_TOPICS.items():
                    if topic == tf_topic and view not in camera_transforms:
                        camera_transforms[view] = {
                            "translation": [
                                float(decoded.translation.x),
                                float(decoded.translation.y),
                                float(decoded.translation.z),
                            ],
                            "quaternion_xyzw": [
                                float(decoded.rotation.x),
                                float(decoded.rotation.y),
                                float(decoded.rotation.z),
                                float(decoded.rotation.w),
                            ],
                        }
                        break
            for view, camera_topic in CAMERA_TOPICS.items():
                if topic == camera_topic:
                    frame = camera_frames[view]
                    frame["indexes"].append(len(frame["indexes"]))
                    frame["timestamps_ns"].append(message.log_time)
                    break

    gripper = summarize_gripper_trace(
        actual_gripper_samples,
        minimum_delta=minimum_delta,
        closed_threshold=closed_threshold,
        minimum_samples=minimum_samples,
    )
    gripper["joint"] = "panda_joint8"
    gripper["topic"] = ROBOT_JOINT_TOPIC
    gripper["command_samples"] = [
        {"timestamp_ns": timestamp, "position": position}
        for timestamp, position in command_gripper_samples
    ]
    warnings = []
    for view, frame in camera_frames.items():
        if not frame["indexes"]:
            warnings.append(f"Missing RGB topic for view {view}")
    if not metadata:
        warnings.append("Missing /meta_data")
    if gripper["status"] == "UNKNOWN":
        warnings.append("Missing panda_joint8 actual gripper trace")
    target = _extract_target(metadata)
    target_projections = {}
    initial_pose = target.get("initial_pose")
    if isinstance(initial_pose, Sequence) and len(initial_pose) >= 3:
        for view in CAMERA_TOPICS:
            calibration = camera_calibration.get(view)
            transform = camera_transforms.get(view)
            if not calibration or not transform:
                continue
            target_projections[view] = project_point_to_image(
                point=initial_pose[:3],
                camera_translation=transform["translation"],
                camera_quaternion_xyzw=transform["quaternion_xyzw"],
                intrinsic_matrix=calibration["K"],
                image_size=(calibration["width"], calibration["height"]),
            )
    return {
        "source_mcap": str(mcap_path),
        "instruction": metadata.get("instruction"),
        "target": target,
        "initial_target_projection_proposals": {
            "status": "UNVERIFIED",
            "views": target_projections,
            "warning": (
                "Coordinate-frame conventions may differ. Visually verify "
                "every proposal before rendering a target marker."
            ),
        },
        "camera_calibration": camera_calibration,
        "initial_camera_transforms": camera_transforms,
        "metadata": metadata,
        "mcap_evaluation": {
            "task_success": metadata.get("task_success"),
            "task_progress": metadata.get("task_progress"),
        },
        "camera_frames": camera_frames,
        "gripper": gripper,
        "warnings": warnings,
    }


def extract_frame_at_index(
    mcap_path: Path,
    view: str,
    frame_index: int,
) -> Image.Image:
    if view not in CAMERA_TOPICS:
        raise ValueError(f"Unknown camera view: {view}")
    if frame_index < 0:
        raise ValueError("frame_index must be non-negative")
    topic = CAMERA_TOPICS[view]
    with mcap_path.open("rb") as stream:
        reader = make_reader(stream, decoder_factories=[DecoderFactory()])
        for index, (_, _, _, decoded) in enumerate(
            reader.iter_decoded_messages(topics=[topic])
        ):
            if index == frame_index:
                return Image.open(io.BytesIO(decoded.data)).convert("RGB")
    raise AnalysisError(
        f"Frame {frame_index} unavailable for {view} in {mcap_path}"
    )


def extract_frames_at_indexes(
    mcap_path: Path,
    view: str,
    frame_indexes: Sequence[int],
) -> dict[int, Image.Image]:
    requested = sorted(set(frame_indexes))
    if not requested:
        return {}
    remaining = set(requested)
    images = {}
    topic = CAMERA_TOPICS[view]
    with mcap_path.open("rb") as stream:
        reader = make_reader(stream, decoder_factories=[DecoderFactory()])
        for index, (_, _, _, decoded) in enumerate(
            reader.iter_decoded_messages(topics=[topic])
        ):
            if index not in remaining:
                continue
            images[index] = Image.open(io.BytesIO(decoded.data)).convert("RGB")
            remaining.remove(index)
            if not remaining:
                break
    if remaining:
        raise AnalysisError(
            f"Frames {sorted(remaining)} unavailable for {view} in {mcap_path}"
        )
    return images


def _font(size: int, *, bold: bool = False) -> ImageFont.ImageFont:
    candidates = [
        (
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
            if bold
            else "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
        ),
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
        if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).is_file():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def render_candidate_sheet(
    *,
    frames: Sequence[tuple[int, Image.Image]],
    view: str,
    output_path: Path,
    columns: int = 4,
) -> dict[str, Any]:
    ordered = sorted(frames, key=lambda item: item[0])
    tile_width = 320
    tile_height = 205
    rows = max(1, math.ceil(len(ordered) / columns))
    canvas = Image.new(
        "RGB", (columns * tile_width, rows * tile_height), (18, 21, 26)
    )
    draw = ImageDraw.Draw(canvas)
    label_font = _font(18, bold=True)
    for cell, (frame_index, image) in enumerate(ordered):
        x = cell % columns * tile_width
        y = cell // columns * tile_height
        thumbnail = image.copy()
        thumbnail.thumbnail(
            (tile_width, tile_height - 30), Image.Resampling.LANCZOS
        )
        canvas.paste(thumbnail, (x, y + 30))
        draw.text(
            (x + 8, y + 4),
            f"{view}  frame={frame_index}",
            font=label_font,
            fill=(245, 223, 85),
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_path, quality=92)
    return {
        "path": str(output_path),
        "view": view,
        "frame_indexes": [item[0] for item in ordered],
    }


def normalize_annotation(annotation: Mapping[str, Any]) -> dict[str, Any]:
    result = dict(annotation)
    geometry = annotation.get("geometry", [])
    if not isinstance(geometry, Sequence):
        raise ValueError("annotation geometry must be a sequence")
    result["geometry"] = [
        min(1.0, max(0.0, float(value))) for value in geometry
    ]
    return result


def _required_mapping(
    value: Any, name: str, errors: list[str]
) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        errors.append(f"{name} must be an object")
        return {}
    return value


def validate_analysis(
    analysis: Mapping[str, Any],
    extracted_signals: Mapping[str, Any],
) -> dict[str, Any]:
    errors = []
    warnings = []
    required = {
        "schema_version",
        "seed",
        "instruction",
        "target",
        "evidence_window",
        "attribution",
        "evidence",
        "evaluation",
        "provenance",
    }
    for field in sorted(required - analysis.keys()):
        errors.append(f"Missing required field: {field}")

    window = _required_mapping(
        analysis.get("evidence_window"), "evidence_window", errors
    )
    frames = window.get("frames")
    if not isinstance(frames, list) or len(frames) != 4:
        errors.append(
            "evidence_window.frames must contain exactly four frames"
        )
        frames = []
    elif frames != sorted(frames) or len(set(frames)) != 4:
        errors.append("Evidence frames must be strictly chronological")

    camera_frames = extracted_signals.get("camera_frames")
    if isinstance(camera_frames, Mapping):
        for view in window.get("views", []):
            view_frames = camera_frames.get(view)
            indexes = (
                view_frames.get("indexes", [])
                if isinstance(view_frames, Mapping)
                else []
            )
            unresolved = [frame for frame in frames if frame not in indexes]
            if unresolved:
                errors.append(f"Unresolved {view} frame indexes: {unresolved}")

    attribution = _required_mapping(
        analysis.get("attribution"), "attribution", errors
    )
    enums = {
        "target_selection": TARGET_SELECTION_VALUES,
        "gripper_action": GRIPPER_ACTION_VALUES,
        "target_interaction": TARGET_INTERACTION_VALUES,
        "object_outcome": OBJECT_OUTCOME_VALUES,
        "cause": CAUSE_VALUES,
    }
    for field, allowed in enums.items():
        value = attribution.get(field)
        if value not in allowed:
            errors.append(f"Invalid {field}: {value}")

    if all(
        attribution.get(field) in allowed for field, allowed in enums.items()
    ):
        errors.extend(
            _cause_consistency_errors(
                attribution,
                analysis.get("evaluation", {}),
            )
        )

    evidence = _required_mapping(analysis.get("evidence"), "evidence", errors)
    if not evidence.get("summary"):
        errors.append("evidence.summary is required")
    interaction_frames = evidence.get("interaction_visible_frames", [])
    if (
        attribution.get("target_interaction") != "UNKNOWN"
        and not interaction_frames
    ):
        errors.append(
            "Definite target interaction requires interaction frames"
        )

    target = extracted_signals.get("target")
    if (
        attribution.get("target_selection") in {"CORRECT", "WRONG_OBJECT"}
        and not target
    ):
        errors.append("Definite target selection requires target metadata")
    if attribution.get("target_selection") == "WRONG_OBJECT":
        if not evidence.get("target_visible_frames"):
            errors.append("WRONG_OBJECT requires target_visible_frames")
        distractor_frames = evidence.get(
            "distractor_interaction_frames", interaction_frames
        )
        if not distractor_frames:
            errors.append(
                "WRONG_OBJECT requires distractor interaction evidence"
            )

    metadata = extracted_signals.get("metadata")
    task_progress = (
        metadata.get("task_progress")
        if isinstance(metadata, Mapping)
        else None
    )
    evaluation = analysis.get("evaluation")
    if (
        isinstance(task_progress, (int, float))
        and task_progress >= 1.0
        and (
            not isinstance(evaluation, Mapping)
            or evaluation.get("success") is not True
        )
    ):
        errors.append(
            "MCAP task_progress=1.0 requires evaluation.success=true"
        )

    outcome = attribution.get("object_outcome")
    if (
        outcome
        in {
            "PUSHED_AWAY",
            "LIFTED_SUCCESSFULLY",
            "LIFTED_THEN_DROPPED",
            "LIFTED_INSUFFICIENTLY",
        }
        and len(evidence.get("outcome_frames", [])) < 2
    ):
        errors.append(f"{outcome} requires a continuous outcome sequence")

    gripper = extracted_signals.get("gripper")
    if isinstance(gripper, Mapping):
        status = gripper.get("status")
        close_intervals = gripper.get("close_intervals", [])
        action = attribution.get("gripper_action")
        if status == "UNKNOWN" and action != "UNKNOWN":
            errors.append(
                "Definite gripper action conflicts with missing trace"
            )
        if (
            status == "AVAILABLE"
            and action == "CLOSE_ATTEMPTED"
            and not close_intervals
        ):
            errors.append("CLOSE_ATTEMPTED conflicts with the available trace")
        if (
            status == "AVAILABLE"
            and action == "NO_CLOSE_ATTEMPT"
            and close_intervals
        ):
            errors.append(
                "NO_CLOSE_ATTEMPT conflicts with the available trace"
            )
    else:
        warnings.append("No gripper summary available")

    return {"valid": not errors, "errors": errors, "warnings": warnings}


def _cause_consistency_errors(
    attribution: Mapping[str, Any],
    evaluation: Any,
) -> list[str]:
    cause = attribution["cause"]
    requirements = {
        "SELECTED_DISTRACTOR": {
            "target_selection": "WRONG_OBJECT",
        },
        "OFF_TARGET_APPROACH": {
            "target_selection": "CORRECT",
            "target_interaction": "NO_CONTACT",
        },
        "NO_CLOSE_ATTEMPT": {
            "target_selection": "CORRECT",
            "gripper_action": "NO_CLOSE_ATTEMPT",
            "target_interaction": "CONTACT_NO_GRASP",
        },
        "MISALIGNED_GRASP": {
            "target_selection": "CORRECT",
            "gripper_action": "CLOSE_ATTEMPTED",
            "target_interaction": "CONTACT_NO_GRASP",
        },
        "UNSTABLE_GRASP": {
            "target_selection": "CORRECT",
            "gripper_action": "CLOSE_ATTEMPTED",
            "target_interaction": "TRANSIENT_GRASP",
        },
        "PREMATURE_GRIPPER_OPENING": {
            "target_selection": "CORRECT",
            "gripper_action": "CLOSE_ATTEMPTED",
            "target_interaction": "TRANSIENT_GRASP",
        },
        "INSUFFICIENT_LIFT_MOTION": {
            "target_selection": "CORRECT",
            "gripper_action": "CLOSE_ATTEMPTED",
            "target_interaction": "STABLE_GRASP",
            "object_outcome": "LIFTED_INSUFFICIENTLY",
        },
    }
    errors = []
    for field, expected in requirements.get(cause, {}).items():
        actual = attribution.get(field)
        if actual != expected:
            errors.append(
                f"Cause {cause} requires {field}={expected}; got {actual}"
            )

    success = (
        evaluation.get("success") if isinstance(evaluation, Mapping) else None
    )
    if cause == "NONE" and success is not True:
        errors.append("Cause NONE requires evaluation.success=true")
    elif success is True and cause != "NONE":
        errors.append(
            f"Cause {cause} conflicts with evaluation.success=true; use NONE"
        )
    return errors


def _format_metric_value(value: Any) -> str:
    if value is None:
        return "N/A"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value).upper()


def format_metric_line(evaluation: Mapping[str, Any]) -> str:
    fields = [
        ("SUCCESS", "success"),
        ("PROGRESS", "progress"),
        ("REACH_PICK", "reach_pick"),
        ("LIFT_PICK", "lift_pick"),
        ("STEPS", "steps"),
        ("STOP", "stop_reason"),
    ]
    return " | ".join(
        f"{label}={_format_metric_value(evaluation.get(key))}"
        for label, key in fields
    )


def attribution_color(label: str) -> tuple[int, int, int]:
    colors = {
        "CORRECT": (42, 130, 218),
        "WRONG_OBJECT": (220, 55, 55),
        "UNCERTAIN": (110, 118, 128),
        "CLOSE_ATTEMPTED": (74, 154, 208),
        "NO_CLOSE_ATTEMPT": (137, 76, 202),
        "NO_CONTACT": (110, 118, 128),
        "CONTACT_NO_GRASP": (235, 132, 32),
        "TRANSIENT_GRASP": (235, 132, 32),
        "STABLE_GRASP": (30, 165, 96),
        "STATIONARY": (110, 118, 128),
        "PUSHED_AWAY": (220, 55, 55),
        "LIFTED_SUCCESSFULLY": (30, 165, 96),
        "LIFTED_THEN_DROPPED": (220, 55, 55),
        "LIFTED_INSUFFICIENTLY": (235, 132, 32),
        "UNKNOWN": (110, 118, 128),
    }
    return colors.get(label, (110, 118, 128))


def _card(
    draw: ImageDraw.ImageDraw,
    box: tuple[int, int, int, int],
    title: str,
    value: str,
    color: tuple[int, int, int],
) -> None:
    draw.rounded_rectangle(
        box, radius=13, fill=(34, 38, 45), outline=color, width=3
    )
    draw.text(
        (box[0] + 16, box[1] + 9),
        title,
        font=_font(20),
        fill=(170, 178, 190),
    )
    draw.text(
        (box[0] + 16, box[1] + 39),
        value,
        font=_font(21, bold=True),
        fill=color,
    )


def _draw_annotations(
    draw: ImageDraw.ImageDraw,
    annotations: Sequence[Mapping[str, Any]],
    *,
    origin: tuple[int, int],
    size: tuple[int, int],
) -> None:
    origin_x, origin_y = origin
    width, height = size
    for raw in annotations:
        annotation = normalize_annotation(raw)
        geometry = annotation.get("geometry", [])
        color = tuple(annotation.get("color", [30, 205, 220]))
        if annotation.get("kind") == "box" and len(geometry) == 4:
            box = (
                origin_x + int(geometry[0] * width),
                origin_y + int(geometry[1] * height),
                origin_x + int(geometry[2] * width),
                origin_y + int(geometry[3] * height),
            )
            draw.rectangle(box, outline=color, width=5)
            if annotation.get("text"):
                text = str(annotation["text"])
                font = _font(19, bold=True)
                text_box = draw.textbbox((0, 0), text, font=font)
                label_width = text_box[2] - text_box[0] + 16
                label_height = text_box[3] - text_box[1] + 10
                label_y = max(2, box[1] - label_height)
                draw.rounded_rectangle(
                    (
                        box[0],
                        label_y,
                        box[0] + label_width,
                        label_y + label_height,
                    ),
                    radius=5,
                    fill=color,
                )
                draw.text(
                    (box[0] + 8, label_y + 2),
                    text,
                    font=font,
                    fill=(255, 255, 255),
                )


def _draw_metric_line(
    draw: ImageDraw.ImageDraw,
    evaluation: Mapping[str, Any],
    start: tuple[int, int],
) -> None:
    fields = [
        ("SUCCESS", "success"),
        ("PROGRESS", "progress"),
        ("REACH_PICK", "reach_pick"),
        ("LIFT_PICK", "lift_pick"),
        ("STEPS", "steps"),
        ("STOP", "stop_reason"),
    ]
    font = _font(18)
    x, y = start
    for index, (label, key) in enumerate(fields):
        value = evaluation.get(key)
        text = f"{label}={_format_metric_value(value)}"
        if value is True:
            color = (30, 165, 96)
        elif value is False:
            color = (220, 55, 55)
        elif value is None:
            color = (110, 118, 128)
        elif key == "stop_reason":
            color = (235, 132, 32)
        else:
            color = (225, 228, 234)
        draw.text((x, y), text, font=font, fill=color)
        text_box = draw.textbbox((0, 0), text, font=font)
        x += text_box[2] - text_box[0]
        if index != len(fields) - 1:
            separator = " | "
            draw.text((x, y), separator, font=font, fill=(150, 158, 170))
            separator_box = draw.textbbox((0, 0), separator, font=font)
            x += separator_box[2] - separator_box[0]


def render_case_image(
    *,
    analysis: Mapping[str, Any],
    images: Mapping[tuple[int, str], Image.Image],
    output_path: Path,
) -> Path:
    width = 1440
    header_height = 295
    row_height = 270
    canvas = Image.new(
        "RGB", (width, header_height + row_height * 4), (18, 21, 26)
    )
    draw = ImageDraw.Draw(canvas)
    draw.text(
        (22, 13),
        f"Seed {analysis['seed']}",
        font=_font(32, bold=True),
        fill=(248, 248, 248),
    )
    draw.text(
        (265, 16),
        "Instruction:",
        font=_font(23, bold=True),
        fill=(112, 190, 255),
    )
    draw.text(
        (410, 16),
        str(analysis["instruction"]),
        font=_font(27),
        fill=(248, 248, 248),
    )

    attribution = analysis["attribution"]
    cards = [
        ("目标选择", attribution["target_selection"]),
        ("夹爪动作", attribution["gripper_action"]),
        ("目标交互", attribution["target_interaction"]),
        ("物体结果", attribution["object_outcome"]),
    ]
    for index, (title, value) in enumerate(cards):
        left = 22 + index * 356
        _card(
            draw,
            (left, 61, left + 326, 143),
            title,
            value,
            attribution_color(value),
        )

    window = analysis["evidence_window"]
    draw.text(
        (22, 160), "证据窗:", font=_font(23, bold=True), fill=(112, 190, 255)
    )
    draw.text(
        (120, 160),
        f"f{window['start_frame']} → f{window['end_frame']}",
        font=_font(23),
        fill=(248, 248, 248),
    )
    draw.text(
        (330, 160), "原因:", font=_font(23, bold=True), fill=(235, 132, 32)
    )
    draw.text(
        (404, 160),
        attribution["cause"],
        font=_font(23),
        fill=(248, 248, 248),
    )
    draw.text(
        (22, 200), "证据:", font=_font(23, bold=True), fill=(235, 132, 32)
    )
    draw.text(
        (96, 200),
        analysis["evidence"]["summary"],
        font=_font(23),
        fill=(225, 228, 234),
    )
    draw.text(
        (22, 240),
        "评测指标:",
        font=_font(23, bold=True),
        fill=(112, 190, 255),
    )
    _draw_metric_line(draw, analysis["evaluation"], (140, 242))

    annotations = analysis.get("annotations", [])
    phase_names = ("approach", "pre_interaction", "interaction", "outcome")
    pending_annotations = []
    for row, frame in enumerate(window["frames"]):
        for column, view in enumerate(("ext1", "ext2", "wrist")):
            left = column * 480
            top = header_height + row * row_height
            image = images.get((frame, view))
            if image is None:
                tile = Image.new("RGB", (480, row_height), (45, 48, 54))
                tile_draw = ImageDraw.Draw(tile)
                tile_draw.text(
                    (120, 120),
                    "VIEW UNAVAILABLE",
                    font=_font(22, bold=True),
                    fill=(190, 190, 190),
                )
            else:
                relevant = [
                    item
                    for item in annotations
                    if item.get("frame") == frame and item.get("view") == view
                ]
                tile = image.resize(
                    (480, row_height), Image.Resampling.LANCZOS
                )
            tile_draw = ImageDraw.Draw(tile)
            tile_draw.rectangle((0, 0, 480, 28), fill=(5, 7, 10))
            tile_draw.text(
                (7, 3),
                f"{phase_names[row]}  f={frame}  {view}",
                font=_font(16),
                fill=(245, 223, 85),
            )
            canvas.paste(tile, (left, top))
            pending_annotations.append(
                (
                    relevant if image is not None else [],
                    (left, top),
                )
            )

    for relevant, origin in pending_annotations:
        _draw_annotations(
            draw,
            relevant,
            origin=origin,
            size=(480, row_height),
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_path, quality=93)
    return output_path


def _distribution(
    records: Sequence[Mapping[str, Any]],
    field: str,
    *,
    analyzed_failure_count: int,
    all_failure_count: int,
) -> dict[str, Any]:
    seeds = defaultdict(list)
    for record in records:
        seeds[record["attribution"][field]].append(record["seed"])
    return {
        label: {
            "count": len(label_seeds),
            "seeds": sorted(label_seeds),
            "analyzed_failure_rate": (
                len(label_seeds) / analyzed_failure_count
                if analyzed_failure_count
                else 0.0
            ),
            "all_failure_rate": (
                len(label_seeds) / all_failure_count
                if all_failure_count
                else 0.0
            ),
        }
        for label, label_seeds in sorted(seeds.items())
    }


def _cross_tab(
    records: Sequence[Mapping[str, Any]],
    row_value,
    column_value,
) -> dict[str, Any]:
    cells = defaultdict(lambda: defaultdict(list))
    for record in records:
        cells[str(row_value(record))][str(column_value(record))].append(
            record["seed"]
        )
    return {
        row: {
            column: {"count": len(seeds), "seeds": sorted(seeds)}
            for column, seeds in sorted(columns.items())
        }
        for row, columns in sorted(cells.items())
    }


def _boolean_label(value: Any) -> str:
    if value is True:
        return "TRUE"
    if value is False:
        return "FALSE"
    return "N/A"


def _progress_bin(value: Any) -> str:
    if not isinstance(value, (int, float)):
        return "N/A"
    if value <= 0:
        return "0"
    if value < 0.5:
        return "(0,0.5)"
    if value < 1:
        return "[0.5,1)"
    return "1"


def aggregate_analyses(
    *,
    eval_result: Mapping[str, Any],
    analyses: Sequence[Mapping[str, Any]],
    validation_results: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    episodes = [
        dict(item)
        for item in eval_result.get("episode_results", [])
        if isinstance(item, Mapping)
    ]
    episodes_by_seed = {
        episode.get("seed"): episode
        for episode in episodes
        if episode.get("seed") is not None
    }
    for record in analyses:
        episode = episodes_by_seed.get(record.get("seed"))
        evaluation = record.get("evaluation")
        if episode is None or not isinstance(evaluation, Mapping):
            continue
        for field in ("success", "progress", "steps", "stop_reason"):
            if field in evaluation:
                episode[field] = evaluation[field]
        criteria_reached = {
            "reach_pick": evaluation.get("reach_pick"),
            "lift_pick": evaluation.get("lift_pick"),
        }
        metrics = dict(episode.get("metrics", {}))
        metrics["criteria_reached"] = criteria_reached
        episode["metrics"] = metrics
    failures = [item for item in episodes if item.get("success") is False]
    successes = [item for item in episodes if item.get("success") is True]
    failure_records = [
        record
        for record in analyses
        if record.get("evaluation", {}).get("success") is not True
    ]
    success_controls = [
        record
        for record in analyses
        if record.get("evaluation", {}).get("success") is True
    ]
    analyzed_failure_count = len(failure_records)
    all_failure_count = len(failures)

    overview_metrics = [extract_evaluation_metrics(item) for item in episodes]
    reach_count = sum(
        metric["reach_pick"] is True for metric in overview_metrics
    )
    lift_count = sum(
        metric["lift_pick"] is True for metric in overview_metrics
    )
    progresses = [
        metric["progress"]
        for metric in overview_metrics
        if isinstance(metric["progress"], (int, float))
    ]
    steps = [
        metric["steps"]
        for metric in overview_metrics
        if isinstance(metric["steps"], (int, float))
    ]
    stop_reasons = Counter(
        metric["stop_reason"] for metric in overview_metrics
    )

    unknown_seeds = sorted(
        record["seed"]
        for record in failure_records
        if "UNKNOWN" in record["attribution"].values()
        or "UNCERTAIN" in record["attribution"].values()
    )
    invalid_seeds = sorted(
        result.get("seed")
        for result in validation_results
        if not result.get("valid", True) and result.get("seed") is not None
    )
    fields = [
        "target_selection",
        "gripper_action",
        "target_interaction",
        "object_outcome",
        "cause",
    ]
    distributions = {
        field: _distribution(
            failure_records,
            field,
            analyzed_failure_count=analyzed_failure_count,
            all_failure_count=all_failure_count,
        )
        for field in fields
    }
    chain_seeds = defaultdict(list)
    for record in failure_records:
        attribution = record["attribution"]
        chain = " → ".join(
            attribution[field]
            for field in (
                "target_selection",
                "gripper_action",
                "target_interaction",
                "object_outcome",
            )
        )
        chain_seeds[chain].append(record["seed"])
    top_chains = [
        {
            "chain": chain,
            "count": len(seeds_for_chain),
            "seeds": sorted(seeds_for_chain),
        }
        for chain, seeds_for_chain in sorted(
            chain_seeds.items(), key=lambda item: (-len(item[1]), item[0])
        )
    ]
    cross_analysis = {
        "target_selection_by_reach_pick": _cross_tab(
            failure_records,
            lambda record: record["attribution"]["target_selection"],
            lambda record: _boolean_label(
                record.get("evaluation", {}).get("reach_pick")
            ),
        ),
        "gripper_action_by_target_interaction": _cross_tab(
            failure_records,
            lambda record: record["attribution"]["gripper_action"],
            lambda record: record["attribution"]["target_interaction"],
        ),
        "target_interaction_by_object_outcome": _cross_tab(
            failure_records,
            lambda record: record["attribution"]["target_interaction"],
            lambda record: record["attribution"]["object_outcome"],
        ),
        "cause_by_target_category": _cross_tab(
            failure_records,
            lambda record: record["attribution"]["cause"],
            lambda record: record.get("target", {}).get("category", "N/A"),
        ),
        "cause_by_progress": _cross_tab(
            failure_records,
            lambda record: record["attribution"]["cause"],
            lambda record: _progress_bin(
                record.get("evaluation", {}).get("progress")
            ),
        ),
    }
    return {
        "provenance_warning": PROVENANCE_WARNING,
        "evaluation": {
            "total": len(episodes),
            "success": len(successes),
            "failure": all_failure_count,
            "success_rate": len(successes) / len(episodes)
            if episodes
            else 0.0,
            "reach_pick": reach_count,
            "lift_pick": lift_count,
            "average_progress": sum(progresses) / len(progresses)
            if progresses
            else None,
            "average_steps": sum(steps) / len(steps) if steps else None,
            "stop_reasons": dict(
                sorted(stop_reasons.items(), key=lambda item: str(item[0]))
            ),
        },
        "coverage": {
            "analyzed_failures": analyzed_failure_count,
            "all_failures": all_failure_count,
            "analysis_rate": analyzed_failure_count / all_failure_count
            if all_failure_count
            else 0.0,
            "unanalyzed_failures": max(
                0, all_failure_count - analyzed_failure_count
            ),
            "unknown_or_uncertain_seeds": unknown_seeds,
            "validation_error_seeds": invalid_seeds,
        },
        "attribution": distributions,
        "top_chains": top_chains,
        "cross_analysis": cross_analysis,
        "success_controls": {
            "count": len(success_controls),
            "seeds": sorted(record["seed"] for record in success_controls),
        },
    }


def _aggregate_label_color(label: str) -> tuple[int, int, int]:
    cause_colors = {
        "NONE": (30, 165, 96),
        "SELECTED_DISTRACTOR": (220, 55, 55),
        "OFF_TARGET_APPROACH": (110, 118, 128),
        "NO_CLOSE_ATTEMPT": (137, 76, 202),
        "MISALIGNED_GRASP": (235, 132, 32),
        "UNSTABLE_GRASP": (220, 55, 55),
        "PREMATURE_GRIPPER_OPENING": (205, 72, 145),
        "INSUFFICIENT_LIFT_MOTION": (220, 170, 45),
        "UNKNOWN": (110, 118, 128),
    }
    return cause_colors.get(label, attribution_color(label))


def _sorted_distribution_entries(
    summary: Mapping[str, Any], field: str
) -> list[tuple[str, Mapping[str, Any]]]:
    entries = summary["attribution"].get(field, {})
    return sorted(
        entries.items(), key=lambda item: (-item[1]["count"], item[0])
    )


def _draw_summary_card(
    draw: ImageDraw.ImageDraw,
    box: tuple[int, int, int, int],
    title: str,
    value: str,
    color: tuple[int, int, int],
) -> None:
    draw.rounded_rectangle(
        box,
        radius=14,
        fill=(34, 38, 45),
        outline=(52, 58, 68),
        width=2,
    )
    draw.text(
        (box[0] + 16, box[1] + 13),
        title,
        font=_font(17),
        fill=(165, 175, 190),
    )
    draw.text(
        (box[0] + 16, box[1] + 43),
        value,
        font=_font(27, bold=True),
        fill=color,
    )


def _draw_dimension_card(
    draw: ImageDraw.ImageDraw,
    *,
    box: tuple[int, int, int, int],
    title: str,
    entries: Sequence[tuple[str, Mapping[str, Any]]],
) -> None:
    draw.rounded_rectangle(
        box,
        radius=16,
        fill=(27, 31, 38),
        outline=(51, 58, 68),
        width=2,
    )
    draw.text(
        (box[0] + 18, box[1] + 14),
        title,
        font=_font(22, bold=True),
        fill=(248, 248, 248),
    )
    draw.text(
        (box[2] - 185, box[1] + 19),
        "数量 · 已分析 · 全失败",
        font=_font(14),
        fill=(145, 154, 168),
    )
    row_y = box[1] + 55
    bar_left = box[0] + 235
    bar_width = 250
    for label, data in entries:
        rate = data["analyzed_failure_rate"]
        color = _aggregate_label_color(label)
        draw.text(
            (box[0] + 18, row_y),
            label,
            font=_font(15, bold=True),
            fill=color,
        )
        draw.rounded_rectangle(
            (bar_left, row_y + 3, bar_left + bar_width, row_y + 22),
            radius=7,
            fill=(48, 54, 63),
        )
        if rate > 0:
            draw.rounded_rectangle(
                (
                    bar_left,
                    row_y + 3,
                    bar_left + max(5, int(bar_width * rate)),
                    row_y + 22,
                ),
                radius=7,
                fill=color,
            )
        metrics = (
            f"{data['count']} · {rate:.1%} · {data['all_failure_rate']:.1%}"
        )
        draw.text(
            (box[2] - 180, row_y),
            metrics,
            font=_font(15),
            fill=(225, 228, 234),
        )
        row_y += 34


def render_aggregate_overview(
    summary: Mapping[str, Any], output_path: Path
) -> Path:
    width = 1440
    margin = 28
    gap = 16
    evaluation = summary["evaluation"]
    coverage = summary["coverage"]
    cause_entries = _sorted_distribution_entries(summary, "cause")
    dimensions = [
        ("目标选择 Target Selection", "target_selection"),
        ("夹爪动作 Gripper Action", "gripper_action"),
        ("目标交互 Target Interaction", "target_interaction"),
        ("物体结果 Object Outcome", "object_outcome"),
    ]
    dimension_entries = [
        (title, _sorted_distribution_entries(summary, field))
        for title, field in dimensions
    ]

    summary_top = 108
    summary_height = 94
    cause_top = summary_top + summary_height + 20
    cause_height = 84 + max(1, len(cause_entries)) * 42
    dimensions_top = cause_top + cause_height + 18
    dimension_width = (width - margin * 2 - gap) // 2
    first_row_height = (
        68
        + max(
            1,
            len(dimension_entries[0][1]),
            len(dimension_entries[1][1]),
        )
        * 34
    )
    second_row_height = (
        68
        + max(
            1,
            len(dimension_entries[2][1]),
            len(dimension_entries[3][1]),
        )
        * 34
    )
    second_row_top = dimensions_top + first_row_height + gap
    chains_top = second_row_top + second_row_height + 18
    chain_entries = summary.get("top_chains", [])[:5]
    chains_height = 78 + max(1, len(chain_entries)) * 46
    status_top = chains_top + chains_height + 18
    status_height = 84
    footer_top = status_top + status_height + 18
    footer_height = 62
    canvas_height = footer_top + footer_height + 24

    canvas = Image.new("RGB", (width, canvas_height), (18, 21, 26))
    draw = ImageDraw.Draw(canvas)
    draw.text(
        (margin, 20),
        "Pick Category 错误归因总览",
        font=_font(34, bold=True),
        fill=(248, 248, 248),
    )
    draw.text(
        (margin, 64),
        (
            f"已分析失败 {coverage['analyzed_failures']}/"
            f"{coverage['all_failures']} · "
            f"覆盖率 {coverage['analysis_rate']:.1%}"
        ),
        font=_font(20),
        fill=(112, 190, 255),
    )

    card_gap = 12
    card_width = (width - margin * 2 - card_gap * 5) // 6
    summary_cards = [
        ("评测总数", str(evaluation["total"]), (112, 190, 255)),
        ("成功", str(evaluation["success"]), (30, 165, 96)),
        ("失败", str(evaluation["failure"]), (220, 55, 55)),
        ("成功率", f"{evaluation['success_rate']:.1%}", (30, 165, 96)),
        (
            "已分析失败",
            str(coverage["analyzed_failures"]),
            (74, 154, 208),
        ),
        ("分析覆盖率", f"{coverage['analysis_rate']:.1%}", (74, 154, 208)),
    ]
    for index, (title, value, color) in enumerate(summary_cards):
        left = margin + index * (card_width + card_gap)
        _draw_summary_card(
            draw,
            (
                left,
                summary_top,
                left + card_width,
                summary_top + summary_height,
            ),
            title,
            value,
            color,
        )

    cause_box = (
        margin,
        cause_top,
        width - margin,
        cause_top + cause_height,
    )
    draw.rounded_rectangle(
        cause_box,
        radius=16,
        fill=(27, 31, 38),
        outline=(51, 58, 68),
        width=2,
    )
    draw.text(
        (margin + 18, cause_top + 14),
        "根因分布 Root Cause",
        font=_font(23, bold=True),
        fill=(248, 248, 248),
    )
    header_y = cause_top + 50
    draw.text(
        (margin + 20, header_y),
        "根因标签",
        font=_font(14),
        fill=(145, 154, 168),
    )
    draw.text(
        (margin + 930, header_y),
        "数量",
        font=_font(14),
        fill=(145, 154, 168),
    )
    draw.text(
        (margin + 1030, header_y),
        "已分析占比",
        font=_font(14),
        fill=(145, 154, 168),
    )
    draw.text(
        (margin + 1200, header_y),
        "全部失败占比",
        font=_font(14),
        fill=(145, 154, 168),
    )
    row_y = cause_top + 76
    bar_left = margin + 340
    bar_width = 540
    for label, data in cause_entries:
        color = _aggregate_label_color(label)
        rate = data["analyzed_failure_rate"]
        draw.text(
            (margin + 20, row_y),
            label,
            font=_font(17, bold=True),
            fill=color,
        )
        draw.rounded_rectangle(
            (bar_left, row_y + 2, bar_left + bar_width, row_y + 24),
            radius=8,
            fill=(48, 54, 63),
        )
        if rate > 0:
            draw.rounded_rectangle(
                (
                    bar_left,
                    row_y + 2,
                    bar_left + max(6, int(bar_width * rate)),
                    row_y + 24,
                ),
                radius=8,
                fill=color,
            )
        draw.text(
            (margin + 940, row_y),
            str(data["count"]),
            font=_font(17, bold=True),
            fill=(248, 248, 248),
        )
        draw.text(
            (margin + 1040, row_y),
            f"{rate:.1%}",
            font=_font(17),
            fill=(225, 228, 234),
        )
        draw.text(
            (margin + 1215, row_y),
            f"{data['all_failure_rate']:.1%}",
            font=_font(17),
            fill=(225, 228, 234),
        )
        row_y += 42

    dimension_boxes = [
        (
            margin,
            dimensions_top,
            margin + dimension_width,
            dimensions_top + first_row_height,
        ),
        (
            margin + dimension_width + gap,
            dimensions_top,
            width - margin,
            dimensions_top + first_row_height,
        ),
        (
            margin,
            second_row_top,
            margin + dimension_width,
            second_row_top + second_row_height,
        ),
        (
            margin + dimension_width + gap,
            second_row_top,
            width - margin,
            second_row_top + second_row_height,
        ),
    ]
    for (title, entries), box in zip(
        dimension_entries, dimension_boxes, strict=True
    ):
        _draw_dimension_card(draw, box=box, title=title, entries=entries)

    chains_box = (
        margin,
        chains_top,
        width - margin,
        chains_top + chains_height,
    )
    draw.rounded_rectangle(
        chains_box,
        radius=16,
        fill=(27, 31, 38),
        outline=(51, 58, 68),
        width=2,
    )
    draw.text(
        (margin + 18, chains_top + 14),
        "Top 失败链路",
        font=_font(23, bold=True),
        fill=(248, 248, 248),
    )
    draw.text(
        (margin + 25, chains_top + 50),
        "排名",
        font=_font(14),
        fill=(145, 154, 168),
    )
    draw.text(
        (margin + 90, chains_top + 50),
        "完整归因链路",
        font=_font(14),
        fill=(145, 154, 168),
    )
    draw.text(
        (margin + 1030, chains_top + 50),
        "数量",
        font=_font(14),
        fill=(145, 154, 168),
    )
    draw.text(
        (margin + 1130, chains_top + 50),
        "Seeds",
        font=_font(14),
        fill=(145, 154, 168),
    )
    row_y = chains_top + 74
    for rank, chain in enumerate(chain_entries, start=1):
        chain_text = chain["chain"]
        if len(chain_text) > 88:
            chain_text = chain_text[:85] + "..."
        draw.text(
            (margin + 30, row_y),
            str(rank),
            font=_font(17, bold=True),
            fill=(112, 190, 255),
        )
        draw.text(
            (margin + 90, row_y),
            chain_text,
            font=_font(16),
            fill=(225, 228, 234),
        )
        draw.text(
            (margin + 1040, row_y),
            str(chain["count"]),
            font=_font(17, bold=True),
            fill=(248, 248, 248),
        )
        seed_text = ", ".join(str(seed) for seed in chain["seeds"][:8])
        if len(chain["seeds"]) > 8:
            seed_text += ", ..."
        draw.text(
            (margin + 1130, row_y),
            seed_text,
            font=_font(15),
            fill=(225, 228, 234),
        )
        row_y += 46

    status_gap = 14
    status_width = (width - margin * 2 - status_gap * 2) // 3
    status_cards = [
        (
            "未分析失败",
            str(coverage["unanalyzed_failures"]),
            (110, 118, 128),
        ),
        (
            "UNKNOWN / UNCERTAIN",
            str(len(coverage["unknown_or_uncertain_seeds"])),
            (235, 132, 32),
        ),
        (
            "校验错误",
            str(len(coverage["validation_error_seeds"])),
            (220, 55, 55),
        ),
    ]
    for index, (title, value, color) in enumerate(status_cards):
        left = margin + index * (status_width + status_gap)
        _draw_summary_card(
            draw,
            (
                left,
                status_top,
                left + status_width,
                status_top + status_height,
            ),
            title,
            value,
            color,
        )

    draw.rounded_rectangle(
        (margin, footer_top, width - margin, footer_top + footer_height),
        radius=13,
        fill=(51, 42, 27),
        outline=(235, 132, 32),
        width=2,
    )
    draw.text(
        (margin + 18, footer_top + 11),
        "说明：错误归因由大模型结合连续多视角图像、夹爪状态、元数据和评测指标生成，",
        font=_font(17),
        fill=(248, 214, 158),
    )
    draw.text(
        (margin + 18, footer_top + 34),
        "不代表人工标注真值；低覆盖率下的分布仅描述已分析案例。",
        font=_font(17),
        fill=(248, 214, 158),
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_path, quality=93)
    return output_path
